FROM byeongal/python:3.12.11-jammy-cuda12.6.3-base

ENV POETRY_HOME=/opt/poetry
ENV PATH="$POETRY_HOME/bin:$PATH"

# https://python-poetry.org/docs/#installing-with-the-official-installer
RUN curl -sSL https://install.python-poetry.org | python3 -