FROM python:3.12.11-bookworm

ENV POETRY_HOME=/opt/poetry
ENV PATH="$POETRY_HOME/bin:$PATH"

# https://python-poetry.org/docs/#installing-with-the-official-installer
RUN curl -sSL https://install.python-poetry.org | python3 -